

debug: false

# own url, used for redirects
url: http://localhost:8080
serve: ':8080'

webauthn:
  relying_party_name: webauthn-demo

session:
  
  key: super-secret-key
  
  domain: localhost
  cookie_name: auth_session

registration:
  allowed: true
  token:

db:
  sqlite_file: storage/database
