version: "2"
services:
  authenticator:
    container_name: authenticator
    build: .
    restart: unless-stopped
    volumes:
      - ./db:/db
    environment:
      U2F_REGISTRATION_ALLOWED: true
      U2F_REGISTRATION_TOKEN: secrettoken
      U2F_DB_SQLITE_FILE: /db/database
      U2F_DEBUG: true
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:auth.stoicatedy.ovh
      - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:max-age=63072000; includeSubDomains; preload
#    networks:
#      - default


#networks:
#  default:
#    external:
#      name: web